# Generated by Django 4.0.6 on 2022-07-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_student_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['group'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
